service: tokenhandlerapi

# Base details for AWS deployment
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  profile: default
  stage: ${self:custom.config.settings.stage}
  apiGateway:
    shouldStartNameWithService: true

custom:
  # Each environment can have its own configuration file
  config: ${file(serverless-environments/${opt:stage, 'local'}.yml)}
  
  # API gateway domain details
  customDomain:
    domainName: ${self:custom.config.settings.apiHostName}
    certificateName: '*.${self:custom.config.settings.certificateDomainName}'
    stage: ${self:custom.config.settings.stage}
    endpointType: regional

  # Scripts used when building the AWS deployment package
  scripts:
    hooks:
      'after:package:createDeploymentArtifacts': npm run customPackager

functions:
  
  # A single CORS handler deals with OPTIONS requests for all endpoints
  options:
    handler: dist/lambda/handlers/options.handler
    events:
      - http: 
          path: /tokenhandler/login/start
          method: options
      - http: 
          path: /tokenhandler/login/end
          method: options
      - http:
          path: /tokenhandler/refresh
          method: options
      - http:
          path: /tokenhandler/logout
          method: options
      - http: 
          path: /tokenhandler/expire
          method: options

  # The main lambda functions do not then require any CORS properties
  startLogin:
    handler: dist/lambda/handlers/startLogin.handler
    events:
      - http: 
          path: /tokenhandler/login/start
          method: post

  endLogin:
    handler: dist/lambda/handlers/endLogin.handler
    events:
      - http: 
          path: /tokenhandler/login/end
          method: post

  refresh:
    handler: dist/lambda/handlers/refresh.handler
    events:
      - http: 
          path: /tokenhandler/refresh
          method: post

  logout:
    handler: dist/lambda/handlers/logout.handler
    events:
      - http:
          path: /tokenhandler/logout
          method: post

  expire:
    handler: dist/lambda/handlers/expire.handler
    events:
      - http: 
          path: /tokenhandler/expire
          method: post

# Exclude files not needed for lambdas, and the custom packager does further work in code
package:
  patterns:
  - '!.vscode/**'
  - '!api.config.json'
  - '!build.sh'
  - '!run.sh'
  - '!aws-packager/**'
  - '!certs/**'
  - '!Dockerfile'
  - '!src/**'
  - '!serverless-environments/**'
  - '!test/**'
  - '!ts*.json'
  - '!package*.json'
  - '!Dockerfile'
  - '!README.md'
  - '!LICENSE.txt'

plugins:
  - serverless-plugin-scripts
  - serverless-domain-manager

# Limit cloudwatch log retention 
resources:
  Resources:
    OptionsLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    StartLoginLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    EndLoginLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    RefreshLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    LogoutLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    ExpireLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'